import { requireAuth, getSupabase, isSupabaseConfigured } from "./supabase-client.js";
import { localStore, persistDeliveries, persistFavorites, removeRemote, loadRemote, syncQueue, migrateLegacyFavorites, saveFinishedRoute, normalize } from "./storage.js";
import { AddressAutocomplete, geocode, getCurrentLocation, createMap, drawRoute, DEFAULT_START } from "./maps.js";
import { optimizeRoute, routeGeometry } from "./routes.js";
import { qs, qsa, toast, uid, formatDistance, setLoading, openDialog, closeDialog } from "./ui.js";

const auth = await requireAuth();
if (!auth) throw new Error("Redirecionando para login");
const state = { user: auth.user, localMode: auth.localMode, deliveries: localStore.getDeliveries(), favorites: [], history: localStore.getRoutes(), start: JSON.parse(localStorage.getItem("luvit:start:v2") || "null") || DEFAULT_START, route: localStore.getActiveRoute(), map: null, navigationMap: null, geometry: null, editingId: null, draggedId: null };
state.favorites = await migrateLegacyFavorites(auth.localMode ? null : auth.user.id);
const userId = auth.localMode ? null : auth.user.id;
let deliveryAutocomplete;
let editAutocomplete;
let startAutocomplete;

function node(tag, className, text) { const element = document.createElement(tag); if (className) element.className = className; if (text != null) element.textContent = text; return element; }
function userName() { return state.user.user_metadata?.name || state.user.email?.split("@")[0] || "entregador"; }
async function saveDeliveries() { await persistDeliveries(state.deliveries, userId); render(); }
async function initializeRemote() { if (state.localMode) return; try { const remote = await loadRemote(userId); if (remote) { state.deliveries = remote.deliveries.length ? remote.deliveries : state.deliveries; state.favorites = remote.favorites.length ? remote.favorites : state.favorites; state.history = remote.routes.length ? remote.routes : state.history; localStore.saveDeliveries(state.deliveries); localStore.saveFavorites(state.favorites); localStore.saveRoutes(state.history); render(); } await syncQueue(); } catch { toast("Seus dados locais estão disponíveis. A sincronização será tentada novamente.", "error"); } }

function render() {
  qs("#delivery-count").textContent = state.deliveries.length; qs("#completed-count").textContent = `${state.deliveries.filter(d => d.status === "completed").length} concluídas`;
  qs("#route-distance").textContent = state.route?.distance ? formatDistance(state.route.distance) : state.geometry?.distance ? formatDistance(state.geometry.distance) : "—";
  qs("#route-status").textContent = state.route ? "Em andamento" : state.deliveries.length ? "Planejando" : "Sem rota"; qs("#location-label").textContent = state.start.label || "Ponto inicial definido";
  renderDeliveries(); renderFavorites(); renderHistory(); updatePrimaryActions(); drawRoute(state.map, state.start, state.deliveries, state.geometry?.geometry || state.route?.geometry); if (state.route) renderNavigation();
}
function renderDeliveries() {
  const list = qs("#delivery-list"); list.replaceChildren();
  if (!state.deliveries.length) { const empty = node("div", "empty-state"); empty.append(node("i", "", "⌖")); const div = node("div"); div.append(node("strong", "", "Nenhuma entrega adicionada"), node("p", "", "Digite um endereço acima para começar a montar sua rota.")); empty.append(div); list.append(empty); return; }
  state.deliveries.forEach((delivery, index) => {
    const item = node("article", "delivery-item"); item.draggable = !matchMedia("(pointer: coarse)").matches; item.dataset.id = delivery.id; const number = node("span", "stop-number", String(index + 1)); const copy = node("div", "delivery-copy"); copy.append(node("strong", "", delivery.address), node("small", "", delivery.notes || delivery.neighborhood || delivery.city || "Aguardando rota")); const actions = node("div", "item-actions");
    const favorite = actionButton(state.favorites.some(f => f.normalized_address === delivery.normalized_address) ? "★" : "☆", "Favoritar", "favorite", delivery.id); const edit = actionButton("✎", "Editar", "edit", delivery.id); const duplicate = actionButton("⧉", "Duplicar", "duplicate", delivery.id, "desktop-action"); const up = actionButton("↑", "Mover para cima", "up", delivery.id, "desktop-action"); const down = actionButton("↓", "Mover para baixo", "down", delivery.id, "desktop-action"); const remove = actionButton("×", "Excluir", "remove", delivery.id);
    const more = document.createElement("details"); more.className = "mobile-more"; const summary = document.createElement("summary"); summary.textContent = "Mais opções"; const menu = node("div", "more-menu"); menu.append(actionButton("⧉", "Duplicar", "duplicate", delivery.id), actionButton("↑", "Mover para cima", "up", delivery.id), actionButton("↓", "Mover para baixo", "down", delivery.id)); more.append(summary, menu);
    actions.append(favorite, edit, duplicate, up, down, remove, more); item.append(number, copy, actions); list.append(item);
  });
}
function actionButton(text, label, action, id, extra = "") { const button = node("button", `icon-button ${extra}`, text); button.type = "button"; button.title = label; button.setAttribute("aria-label", label); button.dataset.action = action; button.dataset.id = id; return button; }
function renderFavorites() { const list = qs("#favorites-list"); list.replaceChildren(); if (!state.favorites.length) return list.append(emptyCard("Nenhum favorito salvo.")); state.favorites.forEach(favorite => { const card = node("article", "saved-card"); const copy = node("div"); copy.append(node("strong", "", favorite.address), node("small", "", favorite.city || "Endereço favorito")); const actions = node("div"); const use = node("button", "button button-primary", "Usar"); use.type = "button"; use.addEventListener("click", () => addFavoriteAsDelivery(favorite)); const remove = actionButton("×", "Remover favorito", "remove-favorite", favorite.id); actions.append(use, remove); card.append(copy, actions); list.append(card); }); }
function renderHistory() { const list = qs("#history-list"); list.replaceChildren(); if (!state.history.length) return list.append(emptyCard("As rotas finalizadas aparecerão aqui.")); state.history.forEach(route => { const card = node("article", "saved-card"); const copy = node("div"); const date = new Date(route.completedAt || route.completed_at || route.created_at); copy.append(node("strong", "", `${route.stops?.length || "Rota"} entregas · ${formatDistance(route.distance || route.total_distance_meters || 0)}`), node("small", "", date.toLocaleString("pt-BR"))); card.append(copy); list.append(card); }); }
function emptyCard(text) { return node("div", "empty-state", text); }

async function addDelivery(data) { const normalized = normalize(data.address); if (state.deliveries.some(d => d.normalized_address === normalized)) return toast("Este endereço já está na lista.", "error"); state.deliveries.push({ id: uid(), address: data.address, normalized_address: normalized, latitude: data.latitude, longitude: data.longitude, neighborhood: data.neighborhood || null, city: data.city || null, state: data.state || null, postcode: data.postcode || null, notes: "", status: "pending" }); qs("#address-input").value = ""; deliveryAutocomplete?.setSelected(null); deliveryAutocomplete?.close(true); await saveDeliveries(); toast("Endereço adicionado.", "success"); }
async function addFavoriteAsDelivery(favorite) { await addDelivery(favorite); setView("deliveries"); }
async function handleItemAction(button) { const delivery = state.deliveries.find(d => d.id === button.dataset.id), index = state.deliveries.indexOf(delivery); if (!delivery) return; switch (button.dataset.action) { case "remove": state.deliveries.splice(index, 1); await removeRemote("deliveries", delivery.id); break; case "duplicate": state.deliveries.splice(index + 1, 0, { ...delivery, id: uid(), address: `${delivery.address} (cópia)`, normalized_address: `${delivery.normalized_address}-copia-${Date.now()}` }); break; case "up": if (index > 0) [state.deliveries[index - 1], state.deliveries[index]] = [delivery, state.deliveries[index - 1]]; break; case "down": if (index < state.deliveries.length - 1) [state.deliveries[index + 1], state.deliveries[index]] = [delivery, state.deliveries[index + 1]]; break; case "edit": state.editingId = delivery.id; qs("#edit-address").value = delivery.address; qs("#edit-notes").value = delivery.notes || ""; editAutocomplete?.setSelected(delivery); openDialog(qs("#edit-dialog"), button); return; case "favorite": await toggleFavorite(delivery); return; } await saveDeliveries(); }
async function toggleFavorite(delivery) { const existing = state.favorites.find(f => f.normalized_address === delivery.normalized_address); if (existing) { state.favorites = state.favorites.filter(f => f.id !== existing.id); await removeRemote("favorites", existing.id); toast("Removido dos favoritos."); } else { state.favorites.unshift({ ...delivery, id: uid(), created_at: new Date().toISOString() }); toast("Endereço favoritado.", "success"); } await persistFavorites(state.favorites, userId); render(); }

async function resolveCoordinates() {
  const unresolved = [];
  const pending = state.deliveries.filter(delivery => delivery.latitude == null);
  const progress = qs("#geocode-progress");
  for (const [index, delivery] of pending.entries()) {
    progress.hidden = false;
    progress.textContent = `Localizando endereços ${index + 1} de ${pending.length}…`;
    try { const point = await geocode(delivery.address, state.start); if (point) Object.assign(delivery, point); else unresolved.push(delivery.address); }
    catch (error) { console.error("[Luvit geocode]", error); unresolved.push(delivery.address); }
  }
  progress.hidden = true;
  await persistDeliveries(state.deliveries, userId);
  const box = qs("#unresolved-list"); box.hidden = !unresolved.length; box.textContent = unresolved.length ? `Não foi possível localizar: ${unresolved.join("; ")}. Edite esses endereços e tente novamente.` : "";
  return state.deliveries.filter(delivery => delivery.latitude != null);
}
async function optimize(button = qs("#optimize-button")) {
  if (state.deliveries.length < 2) return toast("Adicione pelo menos duas entregas para otimizar.", "error");
  setLoading(button, true, "Calculando..."); if (button.id !== "mobile-optimize-button") syncButtonLoading("optimize", true);
  try { const valid = await resolveCoordinates(); if (valid.length < 2) { toast("A rota precisa de pelo menos dois endereços com coordenadas.", "error"); return; } const result = await optimizeRoute(valid, state.start); const invalid = state.deliveries.filter(d => d.latitude == null); state.deliveries = [...result.stops, ...invalid]; state.geometry = result; await saveDeliveries(); toast(result.source === "osrm" ? "Rota otimizada e sequência sugerida." : "Serviço de rota indisponível. Sequência sugerida pelo cálculo local.", "success"); }
  catch (error) { console.error("[Luvit route]", error); toast(navigator.onLine ? "Não foi possível calcular a rota agora." : "Você está offline. Conecte-se para calcular uma nova rota.", "error"); }
  finally { setLoading(button, false); if (button.id !== "mobile-optimize-button") syncButtonLoading("optimize", false); updatePrimaryActions(); }
}
async function refreshGeometry() { const valid = state.deliveries.filter(d => d.latitude != null); if (!valid.length) return; const result = await routeGeometry(valid, state.start); if (result) { state.geometry = result; render(); } }

async function startRoute(trigger = qs("#start-route-button")) { if (!state.deliveries.some(delivery => delivery.latitude != null)) return toast("Adicione ao menos um endereço válido antes de iniciar.", "error"); const valid = await resolveCoordinates(); if (!valid.length) return toast("A rota não possui endereços com coordenadas suficientes.", "error"); if (!state.geometry && valid.length >= 2) await optimize(); state.route = { id: uid(), startedAt: new Date().toISOString(), current: 0, distance: state.geometry?.distance || 0, duration: state.geometry?.duration || 0, geometry: state.geometry?.geometry || null, start: state.start, stops: valid.map(d => ({ ...d, status: "pending" })) }; localStore.saveActiveRoute(state.route); openDialog(qs("#navigation-dialog"), trigger); if (!state.navigationMap) state.navigationMap = createMap("navigation-map"); renderNavigation(); }
function renderNavigation() { const route = state.route; if (!route) return; const index = Math.min(route.current, route.stops.length - 1), current = route.stops[index], next = route.stops[index + 1]; qs("#navigation-progress").textContent = `Parada ${index + 1} de ${route.stops.length}`; qs("#current-address").textContent = current?.address || "Rota concluída"; qs("#next-address").textContent = next ? `Próxima: ${next.address}` : "Esta é a última parada."; qs("#progress-bar").style.width = `${route.stops.length ? (index / route.stops.length) * 100 : 100}%`; qs("#previous-stop").disabled = index === 0; if (state.navigationMap) drawRoute(state.navigationMap, route.start, route.stops.slice(index), route.geometry); }
function updateRoute(status) { const route = state.route, stop = route?.stops[route.current]; if (!stop) return finishRoute(); stop.status = status; if (status === "completed") stop.completedAt = new Date().toISOString(); if (route.current < route.stops.length - 1) route.current += 1; else return finishRoute(); localStore.saveActiveRoute(route); render(); }
async function finishRoute() { if (!state.route || !confirm("Finalizar esta rota? As paradas restantes serão marcadas como puladas.")) return; const route = { ...state.route, completedAt: new Date().toISOString() }; route.stops.forEach(s => { if (s.status === "pending") s.status = "skipped"; }); await saveFinishedRoute(route, userId); state.history.unshift(route); const completedIds = new Set(route.stops.filter(s => s.status === "completed").map(s => s.id)); state.deliveries = state.deliveries.filter(d => !completedIds.has(d.id)); await persistDeliveries(state.deliveries, userId); state.route = null; localStore.saveActiveRoute(null); closeDialog(qs("#navigation-dialog")); render(); toast("Rota finalizada e salva no histórico.", "success"); }
function openNavigation(service) { const stop = state.route?.stops[state.route.current]; if (!stop) return; const query = encodeURIComponent(`${stop.latitude},${stop.longitude}`); const url = service === "waze" ? `https://waze.com/ul?ll=${query}&navigate=yes` : `https://www.google.com/maps/dir/?api=1&destination=${query}`; window.open(url, "_blank", "noopener,noreferrer"); }
function setView(view) { qsa("[data-view]").forEach(button => button.classList.toggle("active", button.dataset.view === view)); qs("#deliveries-view").hidden = view !== "deliveries"; qs(".route-side").hidden = view !== "deliveries"; qs("#favorites-view").hidden = view !== "favorites"; qs("#history-view").hidden = view !== "history"; qs("#mobile-actions").hidden = view !== "deliveries"; if (view === "deliveries") setTimeout(() => state.map?.invalidateSize(), 50); }
function updatePrimaryActions() { const valid = state.deliveries.filter(delivery => delivery.latitude != null).length; qs("#optimize-button").disabled = state.deliveries.length < 2; qs("#mobile-optimize-button").disabled = state.deliveries.length < 2; qs("#start-route-button").disabled = valid < 1; qs("#mobile-start-button").disabled = valid < 1; }
function syncButtonLoading(action, loading) { const button = qs(action === "optimize" ? "#mobile-optimize-button" : "#mobile-start-button"); if (button) setLoading(button, loading, action === "optimize" ? "Calculando..." : "Iniciando..."); }

qs("#greeting").textContent = `Olá, ${userName()}!`; qs("#config-banner").hidden = isSupabaseConfigured(); qs("#sync-status").textContent = state.localMode ? "Salvo neste dispositivo" : "Sincronização ativa";
state.map = createMap("route-map"); render(); initializeRemote().then(refreshGeometry);
const updateConnection = async () => { const online = navigator.onLine; qs("#connection-status").textContent = online ? "Online" : "Offline · dados locais"; qs("#connection-status").classList.toggle("offline", !online); if (online) { const count = await syncQueue(); if (count) toast(`${count} alteração(ões) sincronizada(s).`, "success"); } }; window.addEventListener("online", updateConnection); window.addEventListener("offline", updateConnection); updateConnection();
deliveryAutocomplete = new AddressAutocomplete({ input: "#address-input", list: "#suggestions", getBias: () => state.start, onSelect: result => { if (result) toast("Endereço selecionado.", "success"); } });
editAutocomplete = new AddressAutocomplete({ input: "#edit-address", list: "#edit-suggestions", getBias: () => state.start });
startAutocomplete = new AddressAutocomplete({ input: "#start-address", list: "#start-suggestions", getBias: () => state.start });
qs("#delivery-form").addEventListener("submit", async event => {
  event.preventDefault();
  const input = qs("#address-input"), address = input.value.trim(), button = qs("#add-address-button");
  if (!address) return;
  setLoading(button, true, "Localizando...");
  try {
    let result = deliveryAutocomplete.getSelected();
    if (!result || normalize(result.address) !== normalize(address)) result = await geocode(address, state.start);
    if (!result) return toast("Endereço não localizado. Confira o número, bairro e cidade ou escolha uma sugestão.", "error");
    await addDelivery({ ...result, address: result.address || address });
  } catch (error) {
    console.error("[Luvit geocode]", error);
    toast(error.message === "OFFLINE" ? "Você está offline. Não foi possível validar o endereço." : "Não foi possível consultar endereços agora. Tente novamente.", "error");
  } finally { setLoading(button, false); }
});
document.addEventListener("click", event => { const itemButton = event.target.closest("[data-action]"); if (itemButton) { if (itemButton.dataset.action === "remove-favorite") { state.favorites = state.favorites.filter(f => f.id !== itemButton.dataset.id); removeRemote("favorites", itemButton.dataset.id); persistFavorites(state.favorites, userId).then(render); } else handleItemAction(itemButton); } });
qs("#delivery-list").addEventListener("dragstart", event => { const item = event.target.closest(".delivery-item"); if (!item) return; state.draggedId = item.dataset.id; item.classList.add("dragging"); }); qs("#delivery-list").addEventListener("dragend", event => event.target.closest(".delivery-item")?.classList.remove("dragging")); qs("#delivery-list").addEventListener("dragover", event => event.preventDefault()); qs("#delivery-list").addEventListener("drop", async event => { event.preventDefault(); const targetId = event.target.closest(".delivery-item")?.dataset.id; if (!targetId || targetId === state.draggedId) return; const from = state.deliveries.findIndex(d => d.id === state.draggedId), to = state.deliveries.findIndex(d => d.id === targetId); const [moved] = state.deliveries.splice(from, 1); state.deliveries.splice(to, 0, moved); await saveDeliveries(); });
qs("#edit-form").addEventListener("submit", async event => {
  event.preventDefault();
  if (event.submitter?.value === "cancel") return closeDialog(qs("#edit-dialog"));
  const delivery = state.deliveries.find(d => d.id === state.editingId), address = qs("#edit-address").value.trim(), button = qs("#save-edit-button");
  setLoading(button, true, "Localizando...");
  try { let result = editAutocomplete.getSelected(); if (!result || normalize(result.address) !== normalize(address)) result = await geocode(address, state.start); if (!result) return toast("Endereço não localizado. Confira os dados ou escolha uma sugestão.", "error"); Object.assign(delivery, result, { address: result.address || address, normalized_address: normalize(result.address || address), notes: qs("#edit-notes").value.trim() }); state.geometry = null; closeDialog(qs("#edit-dialog")); await saveDeliveries(); toast("Entrega atualizada.", "success"); }
  catch (error) { console.error("[Luvit geocode]", error); toast(navigator.onLine ? "Não foi possível validar o novo endereço." : "Você está offline. Não foi possível validar o novo endereço.", "error"); }
  finally { setLoading(button, false); }
});
const openStartDialog = event => openDialog(qs("#start-dialog"), event.currentTarget); qs("#manual-start-button").addEventListener("click", openStartDialog); qs("#location-button").addEventListener("click", openStartDialog);
qs("#start-form").addEventListener("submit", async event => { event.preventDefault(); if (event.submitter?.value === "cancel") return closeDialog(qs("#start-dialog")); const button = qs("#save-start-button"); setLoading(button, true, "Localizando..."); try { const address = qs("#start-address").value.trim(); let point = startAutocomplete.getSelected(); if (!point || normalize(point.address) !== normalize(address)) point = await geocode(address, state.start); if (!point) return toast("Não foi possível localizar o ponto inicial.", "error"); state.start = { lat: point.latitude, lon: point.longitude, label: point.address || address }; localStorage.setItem("luvit:start:v2", JSON.stringify(state.start)); state.geometry = null; closeDialog(qs("#start-dialog")); render(); toast("Ponto inicial atualizado.", "success"); } catch (error) { console.error("[Luvit geocode]", error); toast(navigator.onLine ? "Não foi possível localizar o ponto inicial." : "Você está offline. Não foi possível definir o ponto inicial.", "error"); } finally { setLoading(button, false); } });
qs("#use-location-button").addEventListener("click", async event => { setLoading(event.currentTarget, true, "Localizando..."); const location = await getCurrentLocation(); state.start = location; localStorage.setItem("luvit:start:v2", JSON.stringify(location)); state.geometry = null; render(); toast(location.error || "Localização obtida e definida como ponto inicial.", location.error ? "error" : "success"); setLoading(event.currentTarget, false); });
qs("#clear-button").addEventListener("click", async () => { if (state.deliveries.length && confirm("Remover todas as entregas da lista?")) { for (const d of state.deliveries) await removeRemote("deliveries", d.id); state.deliveries = []; state.geometry = null; await saveDeliveries(); } }); qs("#optimize-button").addEventListener("click", event => optimize(event.currentTarget)); qs("#mobile-optimize-button").addEventListener("click", event => optimize(event.currentTarget)); qs("#start-route-button").addEventListener("click", event => startRoute(event.currentTarget)); qs("#mobile-start-button").addEventListener("click", event => startRoute(event.currentTarget)); qsa("[data-view]").forEach(button => button.addEventListener("click", () => setView(button.dataset.view)));
qs("#close-navigation").addEventListener("click", () => closeDialog(qs("#navigation-dialog"))); qs("#complete-stop").addEventListener("click", () => updateRoute("completed")); qs("#skip-stop").addEventListener("click", () => updateRoute("skipped")); qs("#previous-stop").addEventListener("click", () => { if (state.route.current > 0) state.route.current--; localStore.saveActiveRoute(state.route); renderNavigation(); }); qs("#finish-route").addEventListener("click", finishRoute); qs("#open-waze").addEventListener("click", () => openNavigation("waze")); qs("#open-maps").addEventListener("click", () => openNavigation("maps"));
qs("#expand-map").addEventListener("click", () => { qs("#route-map").classList.toggle("expanded-map"); setTimeout(() => state.map?.invalidateSize(), 80); });
qs("#toggle-map").addEventListener("click", event => { const map = qs("#route-map"), open = map.classList.toggle("mobile-map-open"); event.currentTarget.setAttribute("aria-expanded", String(open)); event.currentTarget.textContent = open ? "Fechar mapa" : "Ver mapa"; if (open) window.setTimeout(() => state.map?.invalidateSize(), 80); });
qs("#logout-button").addEventListener("click", async () => { if (getSupabase()) await getSupabase().auth.signOut(); location.replace("/login.html"); });
qsa("dialog").forEach(dialog => dialog.addEventListener("close", () => document.body.classList.remove("modal-open")));
if (state.route) { openDialog(qs("#navigation-dialog")); state.navigationMap = createMap("navigation-map"); renderNavigation(); }
if ("serviceWorker" in navigator && location.protocol !== "file:") navigator.serviceWorker.register("/sw.js");
