import { requireAuth, getSupabase, isSupabaseConfigured } from "./supabase-client.js";
import { localStore, persistDeliveries, persistFavorites, removeRemote, loadRemote, syncQueue, migrateLegacyFavorites, saveFinishedRoute, normalize } from "./storage.js";
import { AddressAutocomplete, getCurrentLocation, createMap, drawRoute, toggleMapLayer, DEFAULT_START } from "./maps.js";
import { geocode, reverseGeocode } from "./services/geocoding.js";
import { optimizeRoute, routeGeometry } from "./routes.js";
import { qs, qsa, toast, uid, setLoading, openDialog, closeDialog } from "./ui.js";
import { createAppState, initialUiState } from "./state/app-state.js";
import { icon } from "./components/icons.js";
import { formatDistance, formatDuration, formatDate, formatTime, plural } from "./utils/format.js";

const auth = await requireAuth();
if (!auth) throw new Error("Redirecionando para login");
const userId = auth.localMode ? null : auth.user.id;
const initialFavorites = await migrateLegacyFavorites(userId);
const savedStart = JSON.parse(localStorage.getItem("luvit:start:v2") || "null") || DEFAULT_START;
const activeRoute = localStore.getActiveRoute();
const store = createAppState({
  ...initialUiState,
  user: auth.user,
  localMode: auth.localMode,
  deliveries: localStore.getDeliveries(),
  favorites: initialFavorites,
  history: localStore.getRoutes(),
  activities: JSON.parse(localStorage.getItem("luvit:activities:v1") || "[]"),
  start: savedStart,
  activeRoute,
  mode: activeRoute ? "driving" : "planning",
  view: activeRoute ? "active" : "dashboard",
  routeGeometry: null,
  selectedStopId: null,
  selectedStopIds: [],
  temporaryPoint: null,
  lastSyncAt: null
});

let plannerMap;
let driverMap;
let drawerAutocomplete;
let drawerSelection;
let drawerMode = "create";
let drawerEditingId = null;
let lastDrawerTrigger;
let draggedStopId;
let mapClickHandler;

const viewMeta = {
  dashboard: ["Operação", "Visão geral", "Acompanhe suas rotas e entregas."],
  planner: ["Planejamento", "Rota de hoje", "Prepare e organize as entregas antes de iniciar."],
  active: ["Execução", "Rota em andamento", "Acompanhe o progresso e conclua cada parada."],
  history: ["Operação", "Histórico", "Consulte as jornadas salvas."],
  favorites: ["Biblioteca", "Favoritos", "Reutilize endereços frequentes."]
};
const statusLabels = { pending: "Pendente", active: "Em atendimento", completed: "Concluída", skipped: "Pulada", problem: "Com problema", cancelled: "Cancelada" };

function el(tag, className, text) { const element = document.createElement(tag); if (className) element.className = className; if (text !== undefined) element.textContent = text; return element; }
function button(label, className = "", action) { const item = el("button", className, label); item.type = "button"; if (action) item.dataset.action = action; return item; }
function iconButton(iconName, label, action) { const item = button("", "icon-button", action); item.setAttribute("aria-label", label); item.title = label; item.append(icon(iconName)); return item; }
function initials() { const source = store.get().user.user_metadata?.name || store.get().user.email || "Luvit"; return source.split(/\s|@/).filter(Boolean).slice(0, 2).map(part => part[0]).join("").toUpperCase(); }
function userName() { return store.get().user.user_metadata?.name || store.get().user.email?.split("@")[0] || "Usuário Luvit"; }
function today(value) { if (!value) return false; const date = new Date(value), now = new Date(); return date.toDateString() === now.toDateString(); }
function saveActivities() { localStorage.setItem("luvit:activities:v1", JSON.stringify(store.get().activities.slice(0, 30))); }
function addActivity(text) { store.update(state => { state.activities.unshift({ id: uid(), text, at: new Date().toISOString() }); state.activities = state.activities.slice(0, 30); return state; }, "activity"); saveActivities(); }
function hydrateIcons(root = document) { qsa("[data-icon]", root).forEach(slot => { const name = slot.dataset.icon; slot.replaceWith(icon(name)); }); }
hydrateIcons();

async function persistStops(reason = "Alterações salvas") {
  store.set({ sync: userId ? "syncing" : "local" }, "sync");
  try { await persistDeliveries(store.get().deliveries, userId); store.set({ sync: userId ? "synced" : "local", lastSyncAt: new Date().toISOString() }, "sync"); }
  catch (error) { console.error("[Luvit sync]", error); store.set({ sync: navigator.onLine ? "error" : "pending" }, "sync"); }
  if (reason) addActivity(reason);
}
async function persistFavoriteList() { try { await persistFavorites(store.get().favorites, userId); } catch (error) { console.error("[Luvit favorites]", error); } }

function renderShell() {
  const state = store.get(), [crumb, title, subtitle] = viewMeta[state.view] || viewMeta.dashboard;
  qs("#breadcrumb").textContent = crumb; qs("#page-title").textContent = title; qs("#page-subtitle").textContent = subtitle;
  qs("#app-shell").classList.toggle("sidebar-collapsed", state.sidebarCollapsed);
  qsa("[data-view-panel]").forEach(panel => panel.classList.toggle("active", panel.dataset.viewPanel === state.view));
  qsa("[data-view]").forEach(control => { const active = control.dataset.view === state.view; control.classList.toggle("active", active); if (active) control.setAttribute("aria-current", "page"); else control.removeAttribute("aria-current"); });
  qsa('[data-view="active"]').forEach(control => control.hidden = !state.activeRoute);
  qs("#sidebar-stop-count").textContent = state.deliveries.length;
  qs("#user-name").textContent = userName(); qs("#user-email").textContent = state.user.email || "Modo local";
  qs("#user-initials").textContent = initials(); qs("#top-user-initials").textContent = initials();
  const connection = state.connection === "online"; qs("#connection-status span:last-child").textContent = connection ? "Online" : "Offline";
  const syncText = state.sync === "syncing" ? "Sincronizando" : state.sync === "pending" ? "Alterações pendentes" : state.sync === "error" ? "Falha na sincronização" : state.sync === "synced" ? "Sincronizado" : "Salvo localmente";
  qs("#sync-status span:last-child").textContent = syncText; qs("#sidebar-sync").textContent = syncText;
  qsa(".sync-dot").forEach(dot => { dot.className = `sync-dot ${state.connection === "offline" ? "offline" : state.sync}`; });
  qs("#config-banner").hidden = isSupabaseConfigured();
}

function renderDashboard() {
  const state = store.get(), todayRoutes = state.history.filter(route => today(route.completedAt || route.completed_at || route.created_at));
  const completed = state.deliveries.filter(stop => stop.status === "completed").length + todayRoutes.reduce((sum, route) => sum + (route.stops?.filter(stop => stop.status === "completed").length || 0), 0);
  qs("#metric-routes-today").textContent = todayRoutes.length + (state.activeRoute ? 1 : 0); qs("#metric-stops-today").textContent = state.deliveries.length; qs("#metric-completed-today").textContent = completed;
  qs("#metric-distance-today").textContent = formatDistance((state.routeGeometry?.distance || 0) + todayRoutes.reduce((sum, route) => sum + (route.distance || route.total_distance_meters || 0), 0) || null);
  const current = qs("#dashboard-current"); current.replaceChildren();
  if (!state.deliveries.length && !state.activeRoute) {
    const empty = el("div", "dashboard-empty"), iconBox = el("div", "empty-icon"); iconBox.append(icon("route")); const content = el("div"); content.append(el("h2", "", "Crie sua primeira rota"), el("p", "", "Adicione as entregas do dia e deixe o Luvit sugerir uma sequência mais eficiente.")); const cta = button("Nova rota", "button button-primary", "new-route"); content.append(cta); empty.append(iconBox, content); current.append(empty);
  } else {
    const header = el("div", "section-header"), copy = el("div"); copy.append(el("h2", "", state.activeRoute ? "Rota em andamento" : "Rota de hoje"), el("p", "", state.activeRoute ? "Continue de onde parou." : "Planejamento salvo automaticamente.")); const open = button(state.activeRoute ? "Continuar rota" : "Abrir planejamento", "button button-primary"); open.dataset.view = state.activeRoute ? "active" : "planner"; header.append(copy, open);
    const metrics = el("div", "summary-metrics"); [["Paradas", state.activeRoute?.stops.length ?? state.deliveries.length], ["Distância", formatDistance(state.activeRoute?.distance ?? state.routeGeometry?.distance)], ["Situação", state.activeRoute ? "Em andamento" : "Planejando"]].forEach(([label, value]) => { const item = el("div"); item.append(el("span", "", label), el("b", "", String(value))); metrics.append(item); }); current.append(header, metrics);
  }
  renderCompactRoutes(); renderDashboardFavorites(); renderActivities();
}
function renderCompactRoutes() { const target = qs("#recent-routes"); target.replaceChildren(); const routes = store.get().history.slice(0, 4); if (!routes.length) return target.append(el("div", "compact-empty", "Nenhuma rota finalizada.")); routes.forEach(route => { const row = el("div", "compact-row"), copy = el("div"); copy.append(el("b", "", route.name || "Rota concluída"), el("small", "", `${formatDate(route.completedAt || route.completed_at)} · ${formatDistance(route.distance || route.total_distance_meters)}`)); row.append(copy, statusBadge("completed")); target.append(row); }); }
function renderDashboardFavorites() { const target = qs("#dashboard-favorites"); target.replaceChildren(); const favorites = store.get().favorites.slice(0, 4); if (!favorites.length) return target.append(el("div", "compact-empty", "Nenhum endereço favorito.")); favorites.forEach(favorite => { const row = el("div", "compact-row"), copy = el("div"); copy.append(el("b", "", favorite.address), el("small", "", [favorite.neighborhood, favorite.city].filter(Boolean).join(" · ") || "Endereço salvo")); const use = iconButton("plus", "Adicionar à rota", "use-favorite"); use.dataset.id = favorite.id; row.append(copy, use); target.append(row); }); }
function renderActivities() { const target = qs("#activity-list"); target.replaceChildren(); const activities = store.get().activities.slice(0, 5); if (!activities.length) return target.append(el("div", "compact-empty", "As alterações recentes aparecerão aqui.")); activities.forEach(activity => { const row = el("div", "activity-row"), copy = el("div"); copy.append(el("b", "", activity.text), el("small", "", `${formatDate(activity.at)} às ${formatTime(activity.at)}`)); row.append(copy); target.append(row); }); }

function filteredStops() { const state = store.get(), term = normalize(state.stopSearch); return state.deliveries.filter(stop => { const matchesSearch = !term || normalize(`${stop.address} ${stop.neighborhood || ""} ${stop.city || ""} ${stop.notes || ""}`).includes(term); const matchesFilter = state.stopFilter === "all" || state.stopFilter === "problem" && (stop.status === "problem" || stop.latitude == null) || stop.status === state.stopFilter; return matchesSearch && matchesFilter; }); }
function statusBadge(status) { return el("span", `status-badge ${status}`, statusLabels[status] || statusLabels.pending); }
function renderPlanner() {
  const state = store.get(), stops = state.deliveries, completed = stops.filter(stop => stop.status === "completed").length;
  qs("#summary-stops").textContent = stops.length; qs("#summary-distance").textContent = formatDistance(state.routeGeometry?.distance); qs("#summary-duration").textContent = formatDuration(state.routeGeometry?.duration); qs("#summary-completed").textContent = completed; qs("#stops-count-badge").textContent = stops.length;
  qs("#summary-sync").textContent = state.lastSyncAt ? `Atualizado ${formatTime(state.lastSyncAt)}` : state.localMode ? "Salvo localmente" : "Aguardando sincronização";
  qs("#planner-view").classList.toggle("map-tab", state.plannerTab === "map"); qsa("[data-planner-tab]").forEach(tab => { const active = tab.dataset.plannerTab === state.plannerTab; tab.classList.toggle("active", active); tab.setAttribute("aria-selected", String(active)); });
  qsa("[data-stop-filter]").forEach(filter => filter.classList.toggle("active", filter.dataset.stopFilter === state.stopFilter));
  renderStopList(); renderInspector(); updatePlannerActions();
  if (state.view === "planner" && (window.innerWidth > 768 || state.plannerTab === "map")) ensurePlannerMap();
}
function renderStopList() {
  const state = store.get(), target = qs("#stop-list"), stops = filteredStops(); target.replaceChildren();
  if (!stops.length) { const empty = el("div", "empty-state"), box = el("div"); const visual = el("div", "empty-icon"); visual.append(icon(state.deliveries.length ? "search" : "route")); box.append(visual, el("h2", "", state.deliveries.length ? "Nenhuma parada encontrada" : "Sua rota ainda está vazia"), el("p", "", state.deliveries.length ? "Altere a busca ou os filtros." : "Adicione o primeiro endereço para começar o planejamento.")); if (!state.deliveries.length) box.append(button("Adicionar parada", "button button-primary", "add-stop")); empty.append(box); target.append(empty); return; }
  const fragment = document.createDocumentFragment();
  stops.forEach(stop => {
    const realIndex = state.deliveries.findIndex(item => item.id === stop.id), selected = state.selectedStopId === stop.id, batch = state.selectedStopIds.includes(stop.id), effectiveStatus = stop.latitude == null ? "problem" : stop.status || "pending";
    const item = el("article", `stop-item ${selected ? "selected" : ""} ${effectiveStatus} ${realIndex === 0 && effectiveStatus === "pending" ? "next" : ""}`); item.dataset.id = stop.id; item.draggable = !matchMedia("(pointer: coarse)").matches;
    const drag = iconButton("drag", "Arrastar para reordenar"); drag.className = "drag-handle"; const checkbox = document.createElement("input"); checkbox.type = "checkbox"; checkbox.className = "stop-select"; checkbox.checked = batch; checkbox.setAttribute("aria-label", `Selecionar parada ${realIndex + 1}`); checkbox.dataset.selectStop = stop.id;
    const number = el("span", "stop-number"); number.textContent = effectiveStatus === "completed" ? "✓" : String(realIndex + 1); const copy = el("div", "stop-copy"); copy.append(el("strong", "", stop.address), el("small", "", [stop.neighborhood, stop.city].filter(Boolean).join(" · ") || (stop.latitude == null ? "Endereço não localizado" : "Destino localizado"))); if (stop.notes) copy.append(el("em", "", stop.notes));
    const menu = document.createElement("details"); menu.className = "stop-menu"; const summary = document.createElement("summary"); summary.setAttribute("aria-label", "Ações da parada"); summary.append(icon("more")); const popover = el("div", "dropdown-menu"); [["edit", "Editar", "edit"], ["duplicate", "Duplicar", "duplicate"], ["favorite", "Favoritar", "favorite"], ["arrowUp", "Mover para cima", "up"], ["arrowDown", "Mover para baixo", "down"], ["trash", "Excluir", "delete"]].forEach(([iconName, label, action]) => { const actionButton = button(label, action === "delete" ? "danger" : ""); actionButton.dataset.stopAction = action; actionButton.dataset.id = stop.id; actionButton.prepend(icon(iconName)); popover.append(actionButton); }); menu.append(summary, popover);
    const status = el("span", `stop-status ${effectiveStatus}`); item.append(checkbox, drag, number, copy, menu, status); item.addEventListener("click", event => { if (event.target.closest("button,summary,input,details")) return; selectStop(stop.id); }); fragment.append(item);
  }); target.append(fragment); renderBulkActions();
}
function renderBulkActions() { const ids = store.get().selectedStopIds; qs("#bulk-actions").hidden = !ids.length; qs("#bulk-count").textContent = ids.length; }
function renderInspector() {
  const state = store.get(), target = qs("#stop-inspector"); target.replaceChildren(); const stop = state.deliveries.find(item => item.id === state.selectedStopId);
  if (!stop) return target.append(routeInspector());
  const position = state.deliveries.findIndex(item => item.id === stop.id) + 1, content = el("div", "inspector-content"), header = el("div", "inspector-header"), title = el("div"); title.append(el("span", "", `Parada ${position}`), el("h2", "", stop.address)); header.append(title, statusBadge(stop.latitude == null ? "problem" : stop.status || "pending"));
  const address = el("section", "inspector-section"); address.append(el("h3", "", "Local"), el("p", "inspector-address", [stop.neighborhood, stop.city, stop.state, stop.postcode].filter(Boolean).join(" · ") || "Detalhes não informados")); if (stop.notes) address.append(el("p", "inspector-note", stop.notes));
  const actions = el("section", "inspector-section inspector-actions"); [["edit", "Editar", "edit"], ["duplicate", "Duplicar", "duplicate"], ["favorite", "Favoritar", "favorite"], ["trash", "Excluir", "delete"]].forEach(([iconName, label, action]) => { const control = button(label, `button ${action === "delete" ? "button-danger-soft" : "button-secondary"}`); control.dataset.stopAction = action; control.dataset.id = stop.id; control.prepend(icon(iconName)); actions.append(control); });
  const order = el("section", "inspector-section"); order.append(el("h3", "", "Posição na rota")); const orderActions = el("div", "inspector-actions"); const up = button("Mover para cima", "button button-secondary"); up.dataset.stopAction = "up"; up.dataset.id = stop.id; const down = button("Mover para baixo", "button button-secondary"); down.dataset.stopAction = "down"; down.dataset.id = stop.id; orderActions.append(up, down); order.append(orderActions);
  const technical = document.createElement("details"); technical.className = "inspector-section technical-details"; const summary = document.createElement("summary"); summary.textContent = "Dados técnicos"; technical.append(summary, el("p", "", stop.latitude != null ? `${Number(stop.latitude).toFixed(6)}, ${Number(stop.longitude).toFixed(6)}` : "Coordenadas indisponíveis")); content.append(header, address, actions, order, technical); target.append(content);
}
function routeInspector() {
  const state = store.get(), content = el("div", "inspector-content"), header = el("div", "inspector-header"), title = el("div"); title.append(el("span", "", "Resumo da rota"), el("h2", "", "Rota de hoje")); header.append(title, statusBadge(state.activeRoute ? "active" : "pending"));
  const metrics = el("section", "inspector-section"); metrics.append(el("h3", "", "Estimativa")); const list = document.createElement("dl"); [["Paradas", state.deliveries.length], ["Distância", formatDistance(state.routeGeometry?.distance)], ["Duração", formatDuration(state.routeGeometry?.duration)], ["Concluídas", state.deliveries.filter(stop => stop.status === "completed").length]].forEach(([term, value]) => { list.append(el("dt", "", term), el("dd", "", String(value))); }); metrics.append(list);
  const start = el("section", "inspector-section"); start.append(el("h3", "", "Ponto inicial")); const row = el("div", "route-start"); row.append(icon("locate")); const copy = el("div"); copy.append(el("b", "", state.start.label || "Ponto inicial"), el("small", "", "Usado para calcular a sequência")); row.append(copy); start.append(row); const change = button("Alterar ponto inicial", "text-button", "change-start"); start.append(change);
  const actions = el("section", "inspector-section inspector-actions"); const optimize = button("Otimizar rota", "button button-secondary primary-span", "optimize"); optimize.disabled = state.deliveries.filter(stop => stop.latitude != null).length < 2; const begin = button("Iniciar rota", "button button-primary primary-span", "start-route"); begin.disabled = !state.deliveries.some(stop => stop.latitude != null); actions.append(optimize, begin); content.append(header, metrics, start, actions); return content;
}
function updatePlannerActions() { const located = store.get().deliveries.filter(stop => stop.latitude != null).length; qsa('[data-action="optimize"],#mobile-optimize').forEach(control => control.disabled = located < 2); qsa('[data-action="start-route"],#mobile-start-route').forEach(control => control.disabled = located < 1); }

function ensurePlannerMap() {
  if (!plannerMap) { plannerMap = createMap("route-map"); mapClickHandler = async event => { if (!store.get().mapSelection) return; await selectManualPoint(event.latlng.lat, event.latlng.lng); }; plannerMap.on("click", mapClickHandler); }
  const state = store.get(); drawRoute(plannerMap, state.start, state.deliveries, state.routeGeometry?.geometry, { selectedStopId: state.selectedStopId, temporaryPoint: state.temporaryPoint, onSelectStop: selectStop }); qs("#map-route-status").textContent = state.routeGeometry ? `${formatDistance(state.routeGeometry.distance)} · ${formatDuration(state.routeGeometry.duration)}` : state.deliveries.length ? "Sequência ainda não calculada" : "Aguardando paradas";
}
function selectStop(id) { store.set({ selectedStopId: id }, "select-stop"); if (innerWidth <= 980) openStopSheet(id); else plannerMap && drawRoute(plannerMap, store.get().start, store.get().deliveries, store.get().routeGeometry?.geometry, { selectedStopId: id, onSelectStop: selectStop, fit: false }); const item = qs(`.stop-item[data-id="${CSS.escape(id)}"]`); item?.scrollIntoView({ block: "nearest" }); }

function setView(view) { const state = store.get(); if (view === "active" && !state.activeRoute) view = "planner"; store.set({ view }, "view"); qs("#sidebar").classList.remove("mobile-open"); qs("#mobile-menu-button").setAttribute("aria-expanded", "false"); if (view === "planner" && (window.innerWidth > 768 || store.get().plannerTab === "map")) requestAnimationFrame(() => ensurePlannerMap()); if (view === "active") requestAnimationFrame(renderDriverMap); }
function renderAll(_, reason) { renderShell(); if (reason !== "select-stop") renderDashboard(); renderPlanner(); renderHistory(); renderFavorites(); renderDriver(); }
store.subscribe(renderAll);

function resetDrawer() { drawerMode = "create"; drawerEditingId = null; drawerSelection = null; qs("#drawer-title").textContent = "Adicionar parada"; qs("#stop-form").reset(); qs("#address-preview").hidden = true; qs("#drawer-message").textContent = ""; drawerAutocomplete?.setSelected(null); drawerAutocomplete?.close(true); }
function openDrawer(trigger, stop = null) { lastDrawerTrigger = trigger || document.activeElement; resetDrawer(); if (stop) { drawerMode = "edit"; drawerEditingId = stop.id; qs("#drawer-title").textContent = "Editar parada"; fillDrawer(stop); drawerSelection = stop; drawerAutocomplete?.setSelected(stop); showAddressPreview(stop); } const drawer = qs("#stop-drawer"); drawer.inert = false; drawer.classList.add("open"); document.body.classList.add("modal-open"); setTimeout(() => qs("#drawer-address").focus(), 100); }
function closeDrawer() { const drawer = qs("#stop-drawer"); drawer.classList.remove("open"); drawer.inert = true; document.body.classList.remove("modal-open"); lastDrawerTrigger?.focus(); }
function fillDrawer(data) { qs("#drawer-address").value = data.address || ""; qs("#drawer-street").value = data.street || String(data.address || "").split(/[,—]/)[0]; qs("#drawer-number").value = data.number || ""; qs("#drawer-complement").value = data.complement || ""; qs("#drawer-neighborhood").value = data.neighborhood || ""; qs("#drawer-city").value = data.city || ""; qs("#drawer-state").value = data.state || ""; qs("#drawer-postcode").value = data.postcode || ""; qs("#drawer-notes").value = data.notes || ""; }
function showAddressPreview(data) { qs("#address-preview").hidden = false; qs("#preview-address").textContent = data.label || data.address; qs("#preview-detail").textContent = data.detail || [data.neighborhood, data.city, data.state].filter(Boolean).join(" · "); }
function drawerData() { const selected = drawerSelection || {}; const street = qs("#drawer-street").value.trim(), number = qs("#drawer-number").value.trim(), details = [qs("#drawer-neighborhood").value.trim(), [qs("#drawer-city").value.trim(), qs("#drawer-state").value.trim()].filter(Boolean).join(" - "), qs("#drawer-postcode").value.trim()].filter(Boolean).join(" · "); const manualAddress = [[street, number].filter(Boolean).join(", "), details].filter(Boolean).join(" — "); return { ...selected, address: selected.address || manualAddress || qs("#drawer-address").value.trim(), street, number, complement: qs("#drawer-complement").value.trim(), neighborhood: qs("#drawer-neighborhood").value.trim(), city: qs("#drawer-city").value.trim(), state: qs("#drawer-state").value.trim(), postcode: qs("#drawer-postcode").value.trim(), notes: qs("#drawer-notes").value.trim() }; }
async function validateDrawerAddress(buttonElement) { let data = drawerData(); if (data.latitude != null && normalize(data.address) === normalize(qs("#drawer-address").value || data.address)) return data; setLoading(buttonElement, true, "Localizando..."); try { const found = await geocode(qs("#drawer-address").value.trim() || data.address, store.get().start); if (!found) throw new Error("NOT_FOUND"); drawerSelection = { ...data, ...found }; fillDrawer(drawerSelection); showAddressPreview(drawerSelection); return drawerSelection; } finally { setLoading(buttonElement, false); } }
async function saveDrawerStop(createAnother = false) { const submit = qs("#save-stop"); qs("#drawer-message").textContent = ""; try { const data = await validateDrawerAddress(submit); if (!data?.address || data.latitude == null) throw new Error("NOT_FOUND"); store.update(state => { if (drawerMode === "edit") { const index = state.deliveries.findIndex(stop => stop.id === drawerEditingId); state.deliveries[index] = { ...state.deliveries[index], ...data, normalized_address: normalize(data.address) }; } else state.deliveries.push({ ...data, id: uid(), normalized_address: normalize(data.address), status: "pending" }); state.routeGeometry = null; return state; }, "stop-save"); if (qs("#drawer-favorite").checked) await addFavorite(data); await persistStops(drawerMode === "edit" ? "Parada atualizada" : "Parada adicionada"); toast(drawerMode === "edit" ? "Parada atualizada." : "Parada adicionada.", "success"); if (createAnother) { resetDrawer(); qs("#drawer-address").focus(); } else closeDrawer(); }
  catch (error) { console.error("[Luvit stop form]", error); qs("#drawer-message").textContent = error.message === "OFFLINE" ? "Você está offline. Escolha uma sugestão já carregada ou tente novamente quando reconectar." : "Endereço não localizado. Confira rua, número e cidade ou marque o ponto no mapa."; }
}
async function addFavorite(data) { if (store.get().favorites.some(favorite => normalize(favorite.address) === normalize(data.address))) return; store.update(state => { state.favorites.unshift({ ...data, id: uid(), normalized_address: normalize(data.address), created_at: new Date().toISOString() }); return state; }, "favorite"); await persistFavoriteList(); }
function startMapSelection() { closeDrawer(); store.set({ mapSelection: true, view: "planner", plannerTab: "map", temporaryPoint: null }, "map-pick"); qs("#route-map").classList.add("map-picking"); qs("#map-selection-hint").hidden = false; toast("Toque no mapa para marcar o local da parada."); }
function stopMapSelection() { store.set({ mapSelection: false, temporaryPoint: null }, "map-pick-cancel"); qs("#route-map").classList.remove("map-picking"); qs("#map-selection-hint").hidden = true; }
async function selectManualPoint(latitude, longitude) { store.set({ temporaryPoint: { latitude, longitude } }, "temporary-point"); try { const found = await reverseGeocode(latitude, longitude); drawerSelection = found; stopMapSelection(); openDrawer(lastDrawerTrigger); drawerSelection = found; fillDrawer(found); qs("#drawer-address").value = found.address; drawerAutocomplete.setSelected(found); showAddressPreview(found); toast("Local marcado no mapa.", "success"); } catch (error) { console.error("[Luvit reverse geocode]", error); stopMapSelection(); drawerSelection = { address: "Local marcado no mapa", label: "Local marcado no mapa", latitude, longitude }; openDrawer(lastDrawerTrigger); fillDrawer(drawerSelection); showAddressPreview(drawerSelection); toast("Ponto marcado. Complete os detalhes do endereço.", "error"); } }

async function calculateOptimization(trigger) {
  const state = store.get(), located = state.deliveries.filter(stop => stop.latitude != null);
  if (!state.start?.lat || !state.start?.lon) return toast("Defina um ponto inicial antes de otimizar.", "error");
  if (located.length < 2) return toast("Localize pelo menos duas paradas antes de otimizar.", "error");
  setLoading(trigger, true, "Calculando...");
  try {
    const before = await routeGeometry(located, state.start); if (!before) throw new Error("CURRENT_ROUTE_UNAVAILABLE");
    const proposal = await optimizeRoute(located, state.start); if (!proposal?.stops?.length) throw new Error("OPTIMIZATION_UNAVAILABLE");
    store.set({ optimizationProposal: { before, after: proposal } }, "optimization-proposal");
    qs("#before-distance").textContent = formatDistance(before.distance); qs("#before-duration").textContent = formatDuration(before.duration); qs("#after-distance").textContent = formatDistance(proposal.distance); qs("#after-duration").textContent = formatDuration(proposal.duration);
    qs("#difference-distance").textContent = `${proposal.distance <= before.distance ? "−" : "+"}${formatDistance(Math.abs(before.distance - proposal.distance))}`; qs("#difference-duration").textContent = `${proposal.duration <= before.duration ? "−" : "+"}${formatDuration(Math.abs(before.duration - proposal.duration))}`;
    openDialog(qs("#optimization-dialog"), trigger);
  } catch (error) { console.error("[Luvit optimization]", error); toast("O serviço de rotas está indisponível. Sua sequência atual foi mantida.", "error"); }
  finally { setLoading(trigger, false); }
}
async function applyOptimization() { const proposal = store.get().optimizationProposal; if (!proposal) return; const locatedIds = new Set(proposal.after.stops.map(stop => stop.id)); const unlocated = store.get().deliveries.filter(stop => !locatedIds.has(stop.id)); store.set({ deliveries: [...proposal.after.stops, ...unlocated], routeGeometry: proposal.after, optimizationProposal: null }, "optimization-apply"); await persistStops("Sequência sugerida aplicada"); closeDialog(qs("#optimization-dialog")); toast("Sequência sugerida aplicada.", "success"); }

async function startRoute(trigger) { const state = store.get(), stops = state.deliveries.filter(stop => stop.latitude != null); if (!stops.length) return toast("Adicione ao menos uma parada localizada.", "error"); let geometry = state.routeGeometry; if (!geometry) geometry = await routeGeometry(stops, state.start); const route = { id: uid(), name: "Rota de hoje", startedAt: new Date().toISOString(), current: 0, distance: geometry?.distance || 0, duration: geometry?.duration || 0, geometry: geometry?.geometry || null, start: state.start, paused: false, stops: stops.map((stop, index) => ({ ...stop, status: index === 0 ? "active" : "pending", started_at: index === 0 ? new Date().toISOString() : null })) }; localStore.saveActiveRoute(route); store.set({ activeRoute: route, mode: "driving", view: "active" }, "route-start"); addActivity("Rota iniciada"); toast("Rota iniciada.", "success"); trigger?.blur(); }
function renderDriver() {
  const target = qs("#driver-experience"), route = store.get().activeRoute; target.replaceChildren(); if (!route) { const empty = el("div", "empty-state"), box = el("div"); const visual = el("div", "empty-icon"); visual.append(icon("navigation")); box.append(visual, el("h2", "", "Nenhuma rota em andamento"), el("p", "", "Inicie uma rota no planejamento para abrir o modo motorista."), button("Abrir planejamento", "button button-primary", "open-planner")); empty.append(box); target.append(empty); return; }
  const currentIndex = Math.min(route.current, route.stops.length - 1), current = route.stops[currentIndex], next = route.stops[currentIndex + 1], done = route.stops.filter(stop => stop.status === "completed").length;
  const layout = el("div", "driver-layout"), panel = el("section", "driver-panel"); const label = el("div", "driver-progress-label"); label.append(el("span", "", `Parada ${currentIndex + 1} de ${route.stops.length}`), el("span", "", `${Math.round(done / route.stops.length * 100)}% concluído`)); const progress = el("div", "driver-progress"), bar = el("span"); bar.style.width = `${done / route.stops.length * 100}%`; progress.append(bar);
  const currentBox = el("div", "driver-current"); currentBox.append(statusBadge(route.paused ? "pending" : "active"), el("h2", "", current.address), el("p", "", [current.neighborhood, current.city].filter(Boolean).join(" · ") || "Parada atual")); if (current.notes) currentBox.append(el("p", "", current.notes));
  const nextBox = el("div", "driver-next"); nextBox.append(el("span", "", "Próxima parada"), el("b", "", next?.address || "Última parada da rota"));
  const actions = el("div", "driver-actions"); const complete = button("Concluir parada", "button button-success driver-primary", "complete-current"); const waze = button("Abrir Waze", "button button-primary", "navigate-waze"); const maps = button("Google Maps", "button button-secondary", "navigate-maps"); const problem = button("Problema", "button button-secondary", "problem-current"); const skip = button("Pular", "button button-secondary", "skip-current"); const pause = button(route.paused ? "Retomar" : "Pausar", "button button-secondary", "pause-route"); actions.append(complete, waze, maps, problem, skip, pause);
  const timeline = el("div", "driver-timeline"); route.stops.forEach((stop, index) => { const item = el("div", `timeline-item ${stop.status}`), dot = el("span", "timeline-dot", stop.status === "completed" ? "✓" : String(index + 1)), copy = el("div"); copy.append(el("b", "", stop.address), el("small", "", statusLabels[stop.status] || "Pendente")); item.append(dot, copy); timeline.append(item); }); panel.append(label, progress, currentBox, nextBox, actions, timeline); const map = el("div", "driver-map"); map.id = "driver-map"; layout.append(panel, map); target.append(layout); if (store.get().view === "active") requestAnimationFrame(renderDriverMap);
}
function renderDriverMap() { const route = store.get().activeRoute; if (!route || !qs("#driver-map")) return; if (driverMap) { driverMap.remove(); driverMap = null; } driverMap = createMap("driver-map"); drawRoute(driverMap, route.start, route.stops.slice(route.current), route.geometry, { selectedStopId: route.stops[route.current]?.id }); }
function openNavigationApp(service) { const route = store.get().activeRoute, stop = route?.stops[route.current]; if (!stop) return; const query = encodeURIComponent(`${stop.latitude},${stop.longitude}`); window.open(service === "maps" ? `https://www.google.com/maps/dir/?api=1&destination=${query}` : `https://waze.com/ul?ll=${query}&navigate=yes`, "_blank", "noopener,noreferrer"); }
function advanceRoute(status, failureReason = null) { const route = structuredClone(store.get().activeRoute); const current = route.stops[route.current]; current.status = status; current.completedAt = new Date().toISOString(); if (failureReason) current.failure_reason = failureReason; if (route.current >= route.stops.length - 1) { localStore.saveActiveRoute(route); store.set({ activeRoute: route }, "route-progress"); return finishRoute(route); } route.current++; route.stops[route.current].status = "active"; route.stops[route.current].started_at = new Date().toISOString(); localStore.saveActiveRoute(route); store.set({ activeRoute: route }, "route-progress"); addActivity(status === "completed" ? "Parada concluída" : status === "problem" ? "Problema registrado" : "Parada pulada"); }
async function finishRoute(routeOverride = null) { const currentRoute = routeOverride || store.get().activeRoute; if (!currentRoute || !confirm("Finalizar esta rota? Paradas pendentes serão registradas como puladas.")) return; const route = structuredClone(currentRoute); route.completedAt = new Date().toISOString(); route.stops.forEach(stop => { if (stop.status === "pending" || stop.status === "active") stop.status = "skipped"; }); await saveFinishedRoute(route, userId); const completedIds = new Set(route.stops.map(stop => stop.id)); store.update(state => { state.history.unshift(route); state.deliveries = state.deliveries.filter(stop => !completedIds.has(stop.id)); state.activeRoute = null; state.mode = "planning"; state.view = "dashboard"; state.routeGeometry = null; return state; }, "route-finish"); localStore.saveActiveRoute(null); localStore.saveDeliveries(store.get().deliveries); addActivity("Rota finalizada"); showRouteSummary(route); }
function showRouteSummary(route) { const target = qs("#route-summary-content"); target.replaceChildren(); const header = el("div"); header.append(el("span", "eyebrow-small", "Jornada finalizada"), el("h2", "", route.name || "Resumo da rota"), el("p", "inspector-note", `${formatDate(route.completedAt)} · ${formatTime(route.startedAt)}–${formatTime(route.completedAt)}`)); const metrics = el("div", "summary-metrics"); [["Duração", formatDuration((new Date(route.completedAt) - new Date(route.startedAt)) / 1000)], ["Distância", formatDistance(route.distance)], ["Concluídas", route.stops.filter(stop => stop.status === "completed").length], ["Puladas", route.stops.filter(stop => stop.status === "skipped").length], ["Problemas", route.stops.filter(stop => stop.status === "problem").length]].forEach(([label, value]) => { const item = el("div"); item.append(el("span", "", label), el("b", "", String(value))); metrics.append(item); }); const footer = el("footer"); const dashboard = button("Voltar ao painel", "button button-secondary", "close-summary"), duplicate = button("Duplicar rota", "button button-primary", "duplicate-finished-route"); duplicate.dataset.id = route.id; footer.append(dashboard, duplicate); target.append(header, metrics, footer); openDialog(qs("#route-summary-dialog")); }

function renderHistory() { const state = store.get(), target = qs("#history-content"), term = normalize(qs("#history-search")?.value || ""), days = +(qs("#history-period")?.value || 0); let routes = state.history.filter(route => !term || normalize(route.name || "Rota concluída").includes(term)); if (days) routes = routes.filter(route => Date.now() - new Date(route.completedAt || route.completed_at || route.created_at) <= days * 86400000); target.replaceChildren(); if (!routes.length) return target.append(emptyState("history", "Nenhuma rota no histórico", "As jornadas finalizadas aparecerão aqui."));
  const table = el("table", "data-table"), thead = document.createElement("thead"), headRow = document.createElement("tr"); ["Data", "Nome", "Paradas", "Distância", "Duração", "Concluídas", "Situação", "Ações"].forEach(label => headRow.append(el("th", "", label))); thead.append(headRow); const tbody = document.createElement("tbody"); routes.forEach(route => { const row = document.createElement("tr"), stops = route.stops || [], actions = el("td", "table-actions"); const details = iconButton("expand", "Abrir detalhes", "history-details"); details.dataset.id = route.id; const duplicate = iconButton("duplicate", "Duplicar rota", "history-duplicate"); duplicate.dataset.id = route.id; const remove = iconButton("trash", "Excluir rota", "history-delete"); remove.dataset.id = route.id; actions.append(details, duplicate, remove); [formatDate(route.completedAt || route.completed_at || route.created_at), route.name || "Rota concluída", stops.length || "—", formatDistance(route.distance || route.total_distance_meters), formatDuration(route.duration || route.estimated_duration_seconds), stops.filter(stop => stop.status === "completed").length || "—"].forEach(value => row.append(el("td", "", String(value)))); const status = document.createElement("td"); status.append(statusBadge("completed")); row.append(status, actions); tbody.append(row); }); table.append(thead, tbody);
  const cards = el("div", "history-cards"); routes.forEach(route => { const card = el("article", "history-card"), header = document.createElement("header"), copy = el("div"); copy.append(el("h3", "", route.name || "Rota concluída"), el("p", "", `${formatDate(route.completedAt || route.completed_at)} · ${formatDistance(route.distance || route.total_distance_meters)}`)); header.append(copy, statusBadge("completed")); const footer = document.createElement("footer"); const open = button("Detalhes", "text-button", "history-details"); open.dataset.id = route.id; const duplicate = button("Duplicar", "text-button", "history-duplicate"); duplicate.dataset.id = route.id; footer.append(open, duplicate); card.append(header, footer); cards.append(card); }); target.append(table, cards);
}
function duplicateHistoryRoute(id) { const route = store.get().history.find(item => item.id === id); if (!route?.stops?.length) return toast("Os detalhes desta rota não estão disponíveis neste dispositivo.", "error"); store.set({ deliveries: route.stops.map(stop => ({ ...stop, id: uid(), status: "pending", completedAt: null, completed_at: null, route_id: null })), routeGeometry: null, view: "planner" }, "route-duplicate"); persistStops("Rota duplicada"); toast("Rota duplicada para o planejamento.", "success"); }
function showHistoryDetails(id) { const route = store.get().history.find(item => item.id === id); if (!route) return; showRouteSummary(route); }

function renderFavorites() { const state = store.get(), target = qs("#favorites-content"), term = normalize(qs("#favorites-search")?.value || ""), city = qs("#favorites-city")?.value || "all"; const cities = [...new Set(state.favorites.map(favorite => favorite.city).filter(Boolean))].sort(); const citySelect = qs("#favorites-city"), currentCity = citySelect.value; citySelect.replaceChildren(new Option("Todas as cidades", "all"), ...cities.map(value => new Option(value, value))); citySelect.value = cities.includes(currentCity) ? currentCity : "all"; const favorites = state.favorites.filter(favorite => (city === "all" || favorite.city === city) && (!term || normalize(`${favorite.address} ${favorite.city || ""} ${favorite.neighborhood || ""}`).includes(term))); target.replaceChildren(); if (!favorites.length) return target.append(emptyState("favorite", "Nenhum favorito encontrado", "Salve endereços frequentes para reutilizá-los rapidamente.")); const fragment = document.createDocumentFragment(); favorites.forEach(favorite => { const row = el("article", "favorite-row"), checkbox = document.createElement("input"); checkbox.type = "checkbox"; checkbox.dataset.favoriteSelect = favorite.id; checkbox.checked = state.selectedFavoriteIds?.includes(favorite.id); const copy = el("div"); copy.append(el("strong", "", favorite.address), el("small", "", [favorite.neighborhood, favorite.city].filter(Boolean).join(" · ") || "Endereço salvo")); const cityCell = el("span", "", favorite.city || "—"), used = el("span", "", favorite.last_used_at ? formatDate(favorite.last_used_at) : "Ainda não usado"), actions = el("div", "table-actions"); const use = iconButton("plus", "Adicionar à rota", "use-favorite"); use.dataset.id = favorite.id; const remove = iconButton("trash", "Excluir favorito", "favorite-delete"); remove.dataset.id = favorite.id; actions.append(use, remove); row.append(checkbox, copy, cityCell, used, actions); fragment.append(row); }); target.append(fragment); qs("#add-selected-favorites").disabled = !(state.selectedFavoriteIds?.length); }
function emptyState(iconName, title, description) { const empty = el("div", "empty-state"), box = el("div"), visual = el("div", "empty-icon"); visual.append(icon(iconName)); box.append(visual, el("h2", "", title), el("p", "", description)); empty.append(box); return empty; }
function useFavorite(id) { const favorite = store.get().favorites.find(item => item.id === id); if (!favorite) return; if (store.get().deliveries.some(stop => normalize(stop.address) === normalize(favorite.address))) return toast("Este endereço já está na rota.", "error"); store.update(state => { state.deliveries.push({ ...favorite, id: uid(), status: "pending", normalized_address: normalize(favorite.address), last_used_at: new Date().toISOString() }); state.routeGeometry = null; state.view = "planner"; return state; }, "favorite-use"); persistStops("Favorito adicionado à rota"); }

function openStopSheet(id) { const stop = store.get().deliveries.find(item => item.id === id); if (!stop || innerWidth > 980) return; const target = qs("#sheet-content"); target.replaceChildren(); const content = el("div", "sheet-address"); content.append(el("span", "eyebrow-small", `Parada ${store.get().deliveries.findIndex(item => item.id === id) + 1}`), el("h2", "", stop.address), el("p", "", [stop.neighborhood, stop.city].filter(Boolean).join(" · ") || "Destino da rota")); const actions = el("div", "sheet-actions"); const edit = button("Editar", "button button-secondary", "sheet-edit"); edit.dataset.id = id; const favorite = button("Favoritar", "button button-secondary", "sheet-favorite"); favorite.dataset.id = id; actions.append(edit, favorite); content.append(actions); target.append(content); const sheet = qs("#stop-sheet"); sheet.inert = false; sheet.classList.add("open"); }
function closeStopSheet() { const sheet = qs("#stop-sheet"); sheet.classList.remove("open"); sheet.inert = true; }

async function handleStopAction(action, id, trigger) { const state = store.get(), index = state.deliveries.findIndex(stop => stop.id === id), stop = state.deliveries[index]; if (!stop) return; if (action === "edit") return openDrawer(trigger, stop); if (action === "duplicate") store.update(next => { next.deliveries.splice(index + 1, 0, { ...stop, id: uid(), address: `${stop.address} (cópia)`, normalized_address: `${stop.normalized_address}-copia-${Date.now()}`, status: "pending" }); next.routeGeometry = null; return next; }, "stop-duplicate"); if (action === "up" && index > 0) store.update(next => { [next.deliveries[index - 1], next.deliveries[index]] = [next.deliveries[index], next.deliveries[index - 1]]; next.routeGeometry = null; return next; }, "stop-up"); if (action === "down" && index < state.deliveries.length - 1) store.update(next => { [next.deliveries[index + 1], next.deliveries[index]] = [next.deliveries[index], next.deliveries[index + 1]]; next.routeGeometry = null; return next; }, "stop-down"); if (action === "favorite") { await addFavorite(stop); toast("Endereço salvo nos favoritos.", "success"); return; } if (action === "delete") { if (!confirm("Excluir esta parada?")) return; store.update(next => { next.deliveries.splice(index, 1); next.selectedStopId = null; next.routeGeometry = null; return next; }, "stop-delete"); await removeRemote("deliveries", id); } await persistStops(action === "duplicate" ? "Parada duplicada" : action === "delete" ? "Parada excluída" : "Sequência alterada"); }
async function handleBulk(action) { const ids = new Set(store.get().selectedStopIds); if (!ids.size) return; if (action === "delete" && !confirm(`Excluir ${plural(ids.size, "parada")} selecionadas?`)) return; store.update(state => { if (action === "delete") state.deliveries = state.deliveries.filter(stop => !ids.has(stop.id)); if (action === "complete") state.deliveries.forEach(stop => { if (ids.has(stop.id)) { stop.status = "completed"; stop.completedAt = new Date().toISOString(); } }); if (action === "end") state.deliveries = [...state.deliveries.filter(stop => !ids.has(stop.id)), ...state.deliveries.filter(stop => ids.has(stop.id))]; state.selectedStopIds = []; state.routeGeometry = null; return state; }, "bulk"); if (action === "delete") for (const id of ids) await removeRemote("deliveries", id); await persistStops("Ação em lote aplicada"); }

function bindEvents() {
  drawerAutocomplete = new AddressAutocomplete({ input: "#drawer-address", list: "#drawer-suggestions", getBias: () => store.get().start, onSelect: result => { drawerSelection = result; if (result) { fillDrawer(result); showAddressPreview(result); toast("Endereço selecionado.", "success"); } } });
  document.addEventListener("click", async event => {
    const viewControl = event.target.closest("[data-view]"); if (viewControl) return setView(viewControl.dataset.view);
    const actionControl = event.target.closest("[data-action]"); if (actionControl) { const action = actionControl.dataset.action; if (action === "new-route") { setView("planner"); return openDrawer(actionControl); } if (action === "add-stop") return openDrawer(actionControl); if (action === "close-drawer") return closeDrawer(); if (action === "cancel-map-selection") return stopMapSelection(); if (action === "optimize") return calculateOptimization(actionControl); if (action === "start-route") return startRoute(actionControl); if (action === "change-start") return changeStart(actionControl); if (action === "navigate-waze") return openNavigationApp("waze"); if (action === "navigate-maps") return openNavigationApp("maps"); if (action === "complete-current") return advanceRoute("completed"); if (action === "skip-current") return advanceRoute("skipped"); if (action === "problem-current") { const reason = prompt("Descreva brevemente o problema:"); if (reason) return advanceRoute("problem", reason); return; } if (action === "pause-route") return togglePause(); if (action === "open-planner") return setView("planner"); if (action === "close-summary") return closeDialog(qs("#route-summary-dialog")); if (action === "duplicate-finished-route") { duplicateHistoryRoute(actionControl.dataset.id); closeDialog(qs("#route-summary-dialog")); return; } if (action === "use-favorite") return useFavorite(actionControl.dataset.id); if (action === "sheet-edit") { const stop = store.get().deliveries.find(item => item.id === actionControl.dataset.id); closeStopSheet(); return openDrawer(actionControl, stop); } if (action === "sheet-favorite") { const stop = store.get().deliveries.find(item => item.id === actionControl.dataset.id); return addFavorite(stop); } }
    const stopAction = event.target.closest("[data-stop-action]"); if (stopAction) return handleStopAction(stopAction.dataset.stopAction, stopAction.dataset.id, stopAction);
    const bulk = event.target.closest("[data-bulk]"); if (bulk) return handleBulk(bulk.dataset.bulk);
    const historyAction = event.target.closest('[data-action^="history-"]'); if (historyAction) { const action = historyAction.dataset.action, id = historyAction.dataset.id; if (action === "history-details") return showHistoryDetails(id); if (action === "history-duplicate") return duplicateHistoryRoute(id); if (action === "history-delete" && confirm("Excluir esta rota do histórico?")) { store.update(state => { state.history = state.history.filter(route => route.id !== id); localStore.saveRoutes(state.history); return state; }, "history-delete"); return removeRemote("routes", id); } }
    if (!event.target.closest(".stop-menu")) qsa(".stop-menu[open]").forEach(menu => menu.removeAttribute("open"));
  });
  document.addEventListener("change", event => { if (event.target.matches("[data-select-stop]")) store.update(state => { const id = event.target.dataset.selectStop; state.selectedStopIds = event.target.checked ? [...new Set([...state.selectedStopIds, id])] : state.selectedStopIds.filter(item => item !== id); return state; }, "batch-select"); if (event.target.matches("[data-favorite-select]")) store.update(state => { const id = event.target.dataset.favoriteSelect; state.selectedFavoriteIds = event.target.checked ? [...new Set([...(state.selectedFavoriteIds || []), id])] : (state.selectedFavoriteIds || []).filter(item => item !== id); return state; }, "favorite-select"); });
  qs("#stop-search").addEventListener("input", event => store.set({ stopSearch: event.target.value }, "stop-search")); qsa("[data-stop-filter]").forEach(control => control.addEventListener("click", () => store.set({ stopFilter: control.dataset.stopFilter }, "stop-filter"))); qsa("[data-planner-tab]").forEach(control => control.addEventListener("click", () => store.set({ plannerTab: control.dataset.plannerTab }, "planner-tab")));
  qs("#stop-list").addEventListener("dragstart", event => { const item = event.target.closest(".stop-item"); if (!item) return; draggedStopId = item.dataset.id; item.classList.add("dragging"); }); qs("#stop-list").addEventListener("dragend", event => event.target.closest(".stop-item")?.classList.remove("dragging")); qs("#stop-list").addEventListener("dragover", event => event.preventDefault()); qs("#stop-list").addEventListener("drop", async event => { event.preventDefault(); const targetId = event.target.closest(".stop-item")?.dataset.id; if (!targetId || targetId === draggedStopId) return; store.update(state => { const from = state.deliveries.findIndex(stop => stop.id === draggedStopId), to = state.deliveries.findIndex(stop => stop.id === targetId), [moved] = state.deliveries.splice(from, 1); state.deliveries.splice(to, 0, moved); state.routeGeometry = null; return state; }, "drag"); await persistStops("Sequência alterada"); });
  qs("#stop-form").addEventListener("submit", event => { event.preventDefault(); saveDrawerStop(false); }); qs("#add-and-another").addEventListener("click", () => saveDrawerStop(true)); qs("#explicit-search").addEventListener("click", async event => { const address = qs("#drawer-address").value.trim(); if (!address) return qs("#drawer-message").textContent = "Digite o endereço completo antes de pesquisar."; setLoading(event.currentTarget, true, "Procurando..."); try { const found = await geocode(address, store.get().start); if (!found) throw new Error("NOT_FOUND"); drawerSelection = found; drawerAutocomplete.setSelected(found); fillDrawer(found); showAddressPreview(found); toast("Endereço localizado.", "success"); } catch { qs("#drawer-message").textContent = "Endereço não localizado. Confira rua, número, bairro e cidade."; } finally { setLoading(event.currentTarget, false); } }); qs("#pick-on-map").addEventListener("click", startMapSelection);
  qs("#apply-optimization").addEventListener("click", event => { event.preventDefault(); applyOptimization(); });
  qs("#collapse-sidebar").addEventListener("click", () => { const collapsed = !store.get().sidebarCollapsed; localStorage.setItem("luvit:sidebar-collapsed", String(collapsed)); store.set({ sidebarCollapsed: collapsed }, "sidebar"); }); qs("#mobile-menu-button").addEventListener("click", event => { const open = qs("#sidebar").classList.toggle("mobile-open"); event.currentTarget.setAttribute("aria-expanded", String(open)); });
  qs("#mobile-more-button").addEventListener("click", event => { const menu = qs("#mobile-more-menu"), open = menu.hidden; menu.hidden = !open; event.currentTarget.setAttribute("aria-expanded", String(open)); }); qs("#top-user-button").addEventListener("click", () => qs(".user-menu").toggleAttribute("open"));
  qs("#mobile-logout").addEventListener("click", logout); qs("#logout-button").addEventListener("click", logout);
  qs("#map-locate").addEventListener("click", async event => { setLoading(event.currentTarget, true); const location = await getCurrentLocation(); setLoading(event.currentTarget, false); if (location.error) return toast(location.error, "error"); store.set({ start: location, routeGeometry: null }, "location"); localStorage.setItem("luvit:start:v2", JSON.stringify(location)); plannerMap?.setView([location.lat, location.lon], 14); toast("Localização atual definida como início.", "success"); }); qs("#map-show-all").addEventListener("click", ensurePlannerMap); qs("#map-layer").addEventListener("click", () => toggleMapLayer(plannerMap)); qs("#map-fullscreen").addEventListener("click", () => { const map = qs("#route-map"); if (!document.fullscreenElement) map.requestFullscreen?.(); else document.exitFullscreen?.(); setTimeout(() => plannerMap?.invalidateSize(), 100); });
  qs("#history-search").addEventListener("input", renderHistory); qs("#history-period").addEventListener("change", renderHistory); qs("#favorites-search").addEventListener("input", renderFavorites); qs("#favorites-city").addEventListener("change", renderFavorites); qs("#add-selected-favorites").addEventListener("click", () => { const ids = store.get().selectedFavoriteIds || []; ids.forEach(useFavorite); store.set({ selectedFavoriteIds: [] }, "favorite-bulk"); });
  qs("#stop-sheet").addEventListener("click", event => { if (event.target.matches(".sheet-backdrop")) closeStopSheet(); }); qs(".sheet-handle").addEventListener("click", () => qs(".sheet-panel").classList.toggle("expanded"));
  qsa("dialog").forEach(dialog => dialog.addEventListener("close", () => document.body.classList.remove("modal-open")));
  document.addEventListener("keydown", event => { if (event.key !== "Escape") return; if (qs("#stop-drawer").classList.contains("open")) closeDrawer(); if (qs("#stop-sheet").classList.contains("open")) closeStopSheet(); if (store.get().mapSelection) stopMapSelection(); });
}
async function changeStart(trigger) { const useCurrent = confirm("Usar sua localização atual? Selecione Cancelar para manter o ponto atual."); if (!useCurrent) return; setLoading(trigger, true, "Localizando..."); const location = await getCurrentLocation(); setLoading(trigger, false); if (location.error) return toast(location.error, "error"); store.set({ start: location, routeGeometry: null }, "start-change"); localStorage.setItem("luvit:start:v2", JSON.stringify(location)); toast("Ponto inicial atualizado.", "success"); }
function togglePause() { const route = structuredClone(store.get().activeRoute); route.paused = !route.paused; route.pausedAt = route.paused ? new Date().toISOString() : null; localStore.saveActiveRoute(route); store.set({ activeRoute: route }, "route-pause"); toast(route.paused ? "Rota pausada." : "Rota retomada.", "success"); }
async function logout() { if (getSupabase()) await getSupabase().auth.signOut(); location.replace("/login.html"); }

async function initializeRemote() { if (auth.localMode) return; store.set({ sync: "syncing" }, "sync"); try { const remote = await loadRemote(userId); if (remote) store.set({ deliveries: remote.deliveries.length ? remote.deliveries : store.get().deliveries, favorites: remote.favorites.length ? remote.favorites : store.get().favorites, history: remote.routes.length ? remote.routes : store.get().history, sync: "synced", lastSyncAt: new Date().toISOString() }, "remote-load"); await syncQueue(); } catch (error) { console.error("[Luvit initialization]", error); store.set({ sync: navigator.onLine ? "error" : "pending" }, "sync"); toast("Dados locais disponíveis. A sincronização será tentada novamente.", "error"); } }
function setupServiceWorker() { if (!("serviceWorker" in navigator) || location.protocol === "file:") return; navigator.serviceWorker.register("/sw.js").then(registration => { registration.addEventListener("updatefound", () => { const worker = registration.installing; worker?.addEventListener("statechange", () => { if (worker.state === "installed" && navigator.serviceWorker.controller) qs("#version-banner").hidden = false; }); }); }); navigator.serviceWorker.addEventListener("controllerchange", () => location.reload()); qs("#reload-app").addEventListener("click", async () => { const registration = await navigator.serviceWorker.getRegistration(); registration?.waiting?.postMessage({ type: "SKIP_WAITING" }); if (!registration?.waiting) location.reload(); }); }

window.addEventListener("online", async () => { store.set({ connection: "online", sync: "syncing" }, "network"); const count = await syncQueue(); store.set({ sync: userId ? "synced" : "local", lastSyncAt: new Date().toISOString() }, "network"); if (count) toast(`${count} alterações sincronizadas.`, "success"); }); window.addEventListener("offline", () => store.set({ connection: "offline", sync: "pending" }, "network"));
bindEvents(); renderAll(store.get(), "initial"); initializeRemote(); setupServiceWorker();
