import { localStore, normalize } from "./storage.js";
const DEFAULT_START = { lat: -25.534, lon: -49.184, label: "São José dos Pinhais (preferência inicial)" };
export function fetchWithTimeout(url, options = {}, timeout = 9000) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout); return fetch(url, { ...options, signal: controller.signal }).finally(() => clearTimeout(timer)); }
export async function searchAddresses(query, bias) { if (query.trim().length < 3 || !navigator.onLine) return []; const params = new URLSearchParams({ q: query, limit: "6", lang: "pt" }); if (bias?.lat) { params.set("lat", bias.lat); params.set("lon", bias.lon); params.set("location_bias_scale", "4"); } const response = await fetchWithTimeout(`https://photon.komoot.io/api/?${params}`); if (!response.ok) throw new Error("Falha na busca"); const data = await response.json(); return (data.features || []).map(feature => { const p = feature.properties, [lon, lat] = feature.geometry.coordinates; const main = [p.name || p.street, p.housenumber].filter(Boolean).join(", "); const detail = [p.district || p.suburb, p.city, p.state].filter(Boolean).join(" · "); return { address: [main, detail].filter(Boolean).join(" — "), label: main || detail, detail, latitude: lat, longitude: lon, neighborhood: p.district || p.suburb || null, city: p.city || null, state: p.state || null }; }); }
export async function geocode(address, bias) { const key = normalize(address), cache = localStore.getGeoCache(); if (cache[key]) return cache[key]; const params = new URLSearchParams({ q: address, format: "jsonv2", limit: "1", addressdetails: "1", "accept-language": "pt-BR" }); if (bias?.lat) params.set("viewbox", `${bias.lon - 2},${bias.lat + 2},${bias.lon + 2},${bias.lat - 2}`); const response = await fetchWithTimeout(`https://nominatim.openstreetmap.org/search?${params}`, { headers: { Accept: "application/json" } }, 10000); if (!response.ok) throw new Error("Serviço de endereços indisponível"); const [item] = await response.json(); if (!item) return null; const result = { latitude: +item.lat, longitude: +item.lon, neighborhood: item.address?.suburb || item.address?.neighbourhood || null, city: item.address?.city || item.address?.town || item.address?.municipality || null, state: item.address?.state || null }; cache[key] = result; localStore.saveGeoCache(cache); return result; }
export function getCurrentLocation() { return new Promise(resolve => { if (!navigator.geolocation) return resolve({ ...DEFAULT_START, error: "Geolocalização não disponível." }); navigator.geolocation.getCurrentPosition(position => resolve({ lat: position.coords.latitude, lon: position.coords.longitude, label: "Minha localização" }), error => resolve({ ...DEFAULT_START, error: error.code === 1 ? "Permissão de localização negada. Escolha o ponto inicial manualmente." : "Não foi possível obter sua localização." }), { enableHighAccuracy: true, timeout: 9000, maximumAge: 300000 }); }); }
export function createMap(elementId) { if (!window.L) return null; const element = document.getElementById(elementId); if (!element) return null; const map = L.map(elementId, { zoomControl: true }).setView([DEFAULT_START.lat, DEFAULT_START.lon], 12); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { maxZoom: 19, attribution: "&copy; OpenStreetMap" }).addTo(map); return map; }
export function drawRoute(map, start, stops, geometry) { if (!map) return; map.eachLayer(layer => { if (!(layer instanceof L.TileLayer)) map.removeLayer(layer); }); const coords = []; if (start) { coords.push([start.lat, start.lon]); L.circleMarker([start.lat, start.lon], { radius: 7, color: "#111827", fillOpacity: 1 }).bindTooltip("Início").addTo(map); } stops.filter(s => s.latitude != null).forEach((stop, index) => { coords.push([stop.latitude, stop.longitude]); L.circleMarker([stop.latitude, stop.longitude], { radius: 8, color: "#fff", weight: 3, fillColor: "#ff5c00", fillOpacity: 1 }).bindTooltip(`${index + 1}. ${stop.address}`).addTo(map); }); if (geometry?.coordinates) L.geoJSON(geometry, { style: { color: "#ff5c00", weight: 5, opacity: .85 } }).addTo(map); else if (coords.length > 1) L.polyline(coords, { color: "#ff5c00", weight: 4, dashArray: "8 8" }).addTo(map); if (coords.length) map.fitBounds(coords, { padding: [35, 35], maxZoom: 15 }); setTimeout(() => map.invalidateSize(), 80); }
export { DEFAULT_START };
