import { getSupabase } from "./supabase-client.js";
import { uid } from "./ui.js";
const KEYS = { deliveries: "luvit:deliveries:v2", favorites: "luvit:favorites:v2", routes: "luvit:routes:v2", active: "luvit:active-route:v2", queue: "luvit:sync-queue:v2", geo: "luvit:geocode-cache:v2", migrated: "luvit:favorites-migrated:v2" };
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
const normalize = address => address.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/\s+/g, " ").trim();
export const localStore = { getDeliveries: () => read(KEYS.deliveries, []), saveDeliveries: value => write(KEYS.deliveries, value), getFavorites: () => read(KEYS.favorites, []), saveFavorites: value => write(KEYS.favorites, value), getRoutes: () => read(KEYS.routes, []), saveRoutes: value => write(KEYS.routes, value), getActiveRoute: () => read(KEYS.active, null), saveActiveRoute: value => value ? write(KEYS.active, value) : localStorage.removeItem(KEYS.active), getGeoCache: () => read(KEYS.geo, {}), saveGeoCache: value => write(KEYS.geo, value) };
function queue(operation) { const list = read(KEYS.queue, []); list.push({ id: uid(), createdAt: new Date().toISOString(), ...operation }); write(KEYS.queue, list); }
async function remote(table, action, payload, match = {}) { const supabase = getSupabase(); if (!supabase) return; let query = supabase.from(table); if (action === "upsert") query = query.upsert(payload); if (action === "delete") { query = query.delete(); Object.entries(match).forEach(([key, value]) => query = query.eq(key, value)); } const { error } = await query; if (error) throw error; }
export async function persistDeliveries(deliveries, userId, online = navigator.onLine) { localStore.saveDeliveries(deliveries); const supabase = getSupabase(); if (!supabase || !userId) return; const rows = deliveries.map((d, position) => ({ id: d.id, user_id: userId, address: d.address, normalized_address: normalize(d.address), latitude: d.latitude, longitude: d.longitude, neighborhood: d.neighborhood || null, city: d.city || null, state: d.state || null, complement: d.complement || null, postcode: d.postcode || null, notes: d.notes || null, failure_reason: d.failure_reason || null, status: d.status || "pending", position, started_at: d.started_at || null, completed_at: d.completedAt || d.completed_at || null })); if (!online) return queue({ table: "deliveries", action: "upsert", payload: rows }); try { if (rows.length) await remote("deliveries", "upsert", rows); } catch (error) { const legacyRows = rows.map(({ complement, postcode, failure_reason, started_at, ...row }) => row); try { if (legacyRows.length) await remote("deliveries", "upsert", legacyRows); } catch { queue({ table: "deliveries", action: "upsert", payload: rows }); } }}
export async function persistFavorites(favorites, userId) { localStore.saveFavorites(favorites); const supabase = getSupabase(); if (!supabase || !userId) return; const rows = favorites.map(f => ({ id: f.id, user_id: userId, address: f.address, normalized_address: normalize(f.address), latitude: f.latitude, longitude: f.longitude })); try { if (rows.length) await remote("favorites", "upsert", rows); } catch { queue({ table: "favorites", action: "upsert", payload: rows }); }}
export async function removeRemote(table, id) { try { await remote(table, "delete", null, { id }); } catch { queue({ table, action: "delete", match: { id } }); } }
export async function loadRemote(userId) { const supabase = getSupabase(); if (!supabase || !navigator.onLine) return null; const [deliveries, favorites, routes] = await Promise.all([supabase.from("deliveries").select("*").eq("user_id", userId).is("route_id", null).order("position"), supabase.from("favorites").select("*").eq("user_id", userId).order("created_at", { ascending: false }), supabase.from("routes").select("*").eq("user_id", userId).order("created_at", { ascending: false }).limit(30)]); if (deliveries.error || favorites.error || routes.error) throw deliveries.error || favorites.error || routes.error; return { deliveries: deliveries.data.map(d => ({ ...d, longitude: d.longitude, latitude: d.latitude })), favorites: favorites.data, routes: routes.data }; }
export async function syncQueue() { const supabase = getSupabase(), items = read(KEYS.queue, []); if (!supabase || !navigator.onLine || !items.length) return 0; const failed = []; for (const item of items) { try { await remote(item.table, item.action, item.payload, item.match); } catch { failed.push(item); } } write(KEYS.queue, failed); return items.length - failed.length; }
export async function migrateLegacyFavorites(userId) { if (read(KEYS.migrated, false)) return localStore.getFavorites(); const legacy = read("luvit_favoritos", []); const current = localStore.getFavorites(); const known = new Set(current.map(f => normalize(f.address))); legacy.forEach(address => { if (typeof address === "string" && !known.has(normalize(address))) current.push({ id: uid(), address, normalized_address: normalize(address), latitude: null, longitude: null, created_at: new Date().toISOString() }); }); write(KEYS.migrated, true); await persistFavorites(current, userId); return current; }
export async function saveFinishedRoute(route, userId) { const routes = [route, ...localStore.getRoutes()].slice(0, 50); localStore.saveRoutes(routes); const supabase = getSupabase(); if (!supabase || !userId) return; const row = { id: route.id, user_id: userId, name: route.name || "Rota de hoje", status: "completed", started_at: route.startedAt, paused_at: route.pausedAt || null, completed_at: route.completedAt, total_distance_meters: Math.round(route.distance || 0), estimated_duration_seconds: Math.round(route.duration || 0), actual_duration_seconds: route.startedAt && route.completedAt ? Math.round((new Date(route.completedAt) - new Date(route.startedAt)) / 1000) : null, start_latitude: route.start?.lat, start_longitude: route.start?.lon }; try { try { await remote("routes", "upsert", row); } catch { const { name, paused_at, actual_duration_seconds, ...legacyRoute } = row; await remote("routes", "upsert", legacyRoute); } for (const stop of route.stops) { let update = { route_id: route.id, status: stop.status === "completed" ? "completed" : "skipped", completed_at: stop.completedAt || route.completedAt, failure_reason: stop.failure_reason || null }; let result = await supabase.from("deliveries").update(update).eq("id", stop.id).eq("user_id", userId); if (result.error) { delete update.failure_reason; result = await supabase.from("deliveries").update(update).eq("id", stop.id).eq("user_id", userId); } if (result.error) throw result.error; } const stops = route.stops.map((stop, position) => ({ id: uid(), route_id: route.id, delivery_id: stop.id, position, status: stop.status === "completed" ? "completed" : "skipped", completed_at: stop.completedAt || null, notes: stop.completionNotes || null })); try { await remote("route_stops", "upsert", stops); } catch { await remote("route_stops", "upsert", stops.map(({ notes, ...stop }) => stop)); } } catch { queue({ table: "routes", action: "upsert", payload: row }); }}
export { normalize };
